addSbtPlugin("org.scala-js"                % "sbt-scalajs"         % "1.4.0")
addSbtPlugin("ch.epfl.scala"               % "sbt-scalajs-bundler" % "0.20.0")
addSbtPlugin("com.geirsson"                % "sbt-ci-release"      % "1.5.5")
addSbtPlugin("org.scalameta"               % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("io.github.davidgregory084"   % "sbt-tpolecat"        % "0.1.16")
resolvers += Resolver.bintrayRepo("oyvindberg", "converter")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter"       % "1.0.0-beta29")
