name: Update Lockfiles

on:
  pull_request:
    types: [labeled]

jobs:
  update-lockfiles:
    name: Update Lockfiles
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'npm dependencies' }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Update root lockfile
        run: yarn install

      - name: Update sbt-managed lockfiles
        run: sbt npmInstallDependencies

      - name: Commit changes
        run: git commit -am "Update lockfiles"
      
      - name: Push
        run: git push
