name: Update Lockfiles

on:
  pull_request:
    types: [labeled]

jobs:
  update-lockfiles:
    name: Update Lockfiles
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'npm dependencies' }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Update root lockfile
        run: yarn install

      - name: Update sbt-managed lockfiles
        run: sbt npmInstallDependencies

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update lockfiles
          commit_user_name: lucuma-steward[bot]
          commit_user_email: 106720676+lucuma-steward[bot]@users.noreply.github.com
